FindImmo/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<pid>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_details'),
    url(r'^result$', views.SearchList, name='search_list'),
    url(r'^advresult$', views.AdvSearchList, name='avcsearch_list'),
    url(r'^(?P<action>[-\w]+)/(?P<Cat_slug>[-\w]+)/(?P<comm>[-\w]+)/$', views.list_vide, name='list_by_category'),
    url(r'^vendre$', views.vendreUnBien, name='vendrebien'),
    url(r'^prestation$', views.nosprestation, name='prestation'),
    url(r'^contact$', views.contacteznous, name='contact'),
    url(r'^search$', views.search, name='search'),
    url(r'^vendeur$', views.vendorform, name='vendeur'),
    url(r'^creation/vendeur/', views.VendorCreate.as_view(), name='creation_vendeur'),
    url(r'^vendeur/(?P<pk>\d+)$', views.VendorDetailView.as_view(), name='vendor-detail'),
]

ImmoCenter/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from FindImmo import views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^acceuil/', include('FindImmo.urls', namespace='shop')),
    url(r'^$', RedirectView.as_view(url='/acceuil/', permanent=True)),
    url('accounts/', include('django.contrib.auth.urls')),
    #url(r'^signup/$', views.signup, name='signup'),
    #url(r'^logindata/$' , views.multiple_forms ,name = 'logindata'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

FindImmo/forms.py
from django.forms import ModelForm
from .models import Category, Product
class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'dimmension', 'localite', 'description', 'price','nbChambre','nbDouche']

FindImmo/views.py
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from .models import Category, Product, Vendor
from django.views import generic
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.contrib import auth
from FindImmo.forms import ProductForm
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from .models import Category, Product, Vendor
from django.db.models import Q
import operator
from django.utils.six.moves import reduce
from .filters import UserFilter, VendorFilter
from django.views.generic.edit import CreateView, UpdateView, DeleteView




def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    Lproducts = Product.objects.filter(available=True,action_type='LOCATION')
    Vproducts = Product.objects.filter(available=True,action_type='VENTE')
    top10=Product.objects.all().order_by('price')[:5]
    #Nvilla = Product.objects.filter(category__name='Beatles Blog')
    queryset = Product.objects.filter(details__slug='aucun',)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        #category = Category.objects.get(slug=category_slug)
        products = products.filter(category=category)
        Lproducts = Product.objects.filter(available=True,action_type='LOCATION',category=category)
        Vproducts = Product.objects.filter(available=True,action_type='VENTE',category=category)
    if category_slug:
        return render(request, 'shop/product/listPerCategory.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products,
                                                      'Lproducts':Lproducts,'Vproducts':Vproducts,})
    else:
        return render(request, 'shop/product/mainpage.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products,
                                                      'top10':top10,'Lproducts':Lproducts,
                                                      'Vproducts':Vproducts,'queryset':queryset,})

    

def list_vide(request, action=None, Cat_slug=None, comm=None):
    prod= None
    prod1= None
    prod2= None
    if Cat_slug != 'all':
        categories = Category.objects.all()
        prod = Product.objects.filter(action_type=action, available=True)
        prod1 = prod.filter(category__slug = Cat_slug)
        prod2 = prod1.filter(commdt=comm)
        return render(request, 'shop/product/list1.html', {'prod1': prod1, 'prod2': prod2, 'categories':categories})
    else:
        categories = Category.objects.all()
        prod = Product.objects.filter(action_type=action, available=True)
        return render(request, 'shop/product/list1.html', {'prod': prod, 'categories':categories})

def product_detail(request, pid, slug):
    product = get_object_or_404(Product, id=pid, slug=slug, available=True)
    JoinProddetails = product.details.all()
    categories = Category.objects.all()
    queryset_list = Product.objects.all()
    like_queryset_list = queryset_list.filter(Q(description__icontains=product.description))
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,'categories': categories,'like_queryset_list':like_queryset_list,
                  'JoinProddetails':JoinProddetails,})

def qsearch(*argv):
    return len(argv[0])

def SearchList(request):
    lqueryset_list = ""
    vqueryset_list = ""
    commTab = []
    filters = []
    filtre = Q()
    queryset_list = Product.objects.all()
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    Lproducts = Product.objects.filter(available=True,action_type='LOCATION')
    Vproducts = Product.objects.filter(available=True,action_type='VENTE')
    act = request.GET.get('actId')
    vquery = request.GET.get('v_KeyWords')
    lquery = request.GET.get('l_KeyWords')
    l_localite = request.GET.get('l_local')
    l_typeBien = request.GET.get('l_type')
    l_toilette = request.GET.get('l_douche')
    l_Nchambre = request.GET.get('l_chambre')
    l_prixmin = request.GET.get('l_pmin')
    l_prixmax = request.GET.get('l_pmax')
    v_localite = request.GET.get('v_local')
    v_typeBien = request.GET.get('v_type')
    v_toilette = request.GET.get('v_douche')
    v_Nchambre = request.GET.get('v_chambre')
    v_prixmin = request.GET.get('v_pmin')
    v_prixmax = request.GET.get('v_pmax')

    # douche_ext = request.GET.get('douext')
    # aucun = request.GET.get('aucun')
    # depen_ext = request.GET.get('depext')
    # clim = request.GET.get('clim')
    # chauff_eau = request.GET.get('chauffo')
    # gason_jardin = request.GET.get('gazonjar')

    # if douche_ext != None:
    #     commTab.append(douche_ext)
    #     filters.append(Q(details__slug=douche_ext,))
    #     filtre &= Q(details__slug=douche_ext,)
    # if aucun != None:
    #     commTab.append(aucun)
    #     filters.append(Q(details__slug=aucun,))
    #     filtre &= Q(details__slug=aucun,)
    # if depen_ext != None:
    #     commTab.append(depen_ext)
    #     filters.append(Q(details__slug=depen_ext,))
    #     filtre &= Q(details__slug=depen_ext,)
    # if clim != None:
    #     commTab.append(clim)
    #     filters.append(Q(details__slug=clim,))
    #     filtre &= Q(details__slug=clim,)
    # if chauff_eau != None:
    #     commTab.append(chauff_eau)
    #     filters.append(Q(details__slug=chauff_eau,))
    #     filtre &= Q(details__slug=chauff_eau,)
    # if gason_jardin != None:
    #     commTab.append(gason_jardin)
    #     filters.append(Q(details__slug=gason_jardin,))
    #     filtre &= Q(details__slug=gason_jardin,)

    #queryset = queryset_list.filter(filtre)
    #queryset = queryset_list.filter(Q(details__slug__icontains=clim))    
    
    #for arg in commTab:
       # filtre &= Q(details__slug__icontains=arg)
    
    #queryset = Product.objects.filter(reduce(operator.iand, filters))
    #lglobquery = Q(localite__localite__icontains=l_localite) | Q(category__name__icontains=l_typeBien)|Q(nbDouche__exact=l_toilette) | Q(nbChambre__exact=l_Nchambre) | (Q(price__gte=l_prixmin) & Q(price__lte=l_prixmax)) | Q(localite__localite__icontains=lquery)
    if act == "louer":
        if (lquery=="" and l_localite=="" and l_typeBien=="" and l_toilette=="" and l_Nchambre=="" and l_prixmin=="" and l_prixmax==""):
            return render(request,'shop/product/searchlist.html',{'act':act,'categories':categories,'Lproducts':Lproducts,})
        else:
            lqueryset_list = queryset_list.filter(Q(localite__localite__icontains=l_localite),Q(category__name__icontains=l_typeBien),
                                                  Q(description__icontains=lquery),action_type__iexact='LOCATION')
            #lqueryset_list = queryset_list.filter(Q(details__slug__icontains='climatisation'),action_type__iexact='LOCATION')
            
            return render(request,'shop/product/searchlist.html',{'categories':categories,'lqueryset_list':lqueryset_list,})  
    if act == "vendre":
        if not (vquery and v_localite and v_typeBien and v_toilette and v_Nchambre and v_prixmin and v_prixmax):
            return render(request,'shop/product/searchlist.html',{'act':act,'categories':categories,'Vproducts':Vproducts,})
        else:
            vqueryset_list = queryset_list.filter(Q(localite__localite__icontains=v_localite),Q(category__name__icontains=v_typeBien),
                                                  Q(description__icontains=vquery),action_type__startswith='VENTE')
            return render(request,'shop/product/searchlist.html',{'categories':categories,'vqueryset_list':vqueryset_list,})
def AdvSearchList(request):
    prodform = ProductForm()
    categories = Category.objects.all()
    return render(request,'shop/product/advancedSearch.html',{'categories':categories,'prodform':prodform,})
    #return render(request,'shop/product/advancedSearch.html',{'categories':categories,'prodform':prodform,'douche_ext':douche_ext,
       # 'depen_ext':depen_ext,'clim':clim,'chauff_eau':chauff_eau,'gason_jardin':gason_jardin,'aucun':aucun,})

def vendreUnBien(request):
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    return render(request, 'shop/product/vendre1.html', {'products': products,'categories':categories})

def nosprestation(request):
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    return render(request, 'shop/product/prestation.html', {'products': products,'categories':categories})

def contacteznous(request):
    contact = Vendor.objects.all()
    categories = Category.objects.all()
    return render(request, 'shop/product/contact.html', {'contact': contact,'categories':categories,})

def search(request):
    product_list1 = Product.objects.all()
    categories = Category.objects.all()
    product_filter = UserFilter(request.GET, queryset=product_list1)
    return render(request, 'shop/product/user_list.html', {'filter': product_filter,'categories':categories})

def vendorform(request):
    vendorInfo = Vendor.objects.all()
    categories = Category.objects.all()
    vendor_filter = VendorFilter(request.GET, queryset=vendorInfo)
    return render(request, 'shop/product/vendor_list.html', {'filter': vendor_filter,'categories':categories})

class VendorDetailView(generic.DetailView):
    model = Vendor
    template_name = 'shop/product/vendor_detail.html'

class VendorCreate(CreateView):
    model = Vendor
    fields = '__all__'
    template_name = 'shop/product/vendor_form.html'

FindImmo/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}My shop{% endblock %}</title>
    {% load static %}
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link rel="shortcut icon" href="{%  static "img/favicon.ico" %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div id="header">
        <img src="{% static '/img/shop1.png' %}" alt="My image" style="width:450px;"/>
        <img src="{% static '/img/imagesP3_large.png' %}" alt="My image" style="width:450px;"/>
        <img src="{% static '/img/imagesP4.png' %}" alt="My image" style="width:440px;"/>
    </div>
    <div id="subheader">
        <a href="/" class="logo">Ma Boutique</a>
        <div class="search-container">
            <form action="{% url "shop:search_list" %}" method="get" accept-charset="utf-8">
              <select id="SearchType" name = 'st'>
                <option value="book">Book</option>
                <option value="author">Author</option>
              </select>
              <input id="searchbox" name="q" type="text" placeholder="Search">
              <button type="submit" value="Search"><i class="fa fa-search"></i></button> 
            </form>
        </div>
        <div class="cart">
            {% if user.is_authenticated %}
                <a><span class="glyphicon glyphicon-user"></span> Salut! {{ user.get_username }}</a><br>
            {% else %}
                <a><span class="glyphicon glyphicon-user"></span> Salut! <a href="{% url "logindata" %}">S'identifier</a><br>
            {% endif %}
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Votre Panier:<span class="glyphicon glyphicon-shopping-cart"></span> 
                    <a href="{% url "cart:cart_detail" %}">
                        {{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price|floatformat:"0"}}
                    </a>
                {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
        </div>
    </div>
    {% block content %}
    {% endblock %}
<script>
    function myFunction(imgs) {
        var expandImg = document.getElementById("expandedImg");
        var imgText = document.getElementById("imgtext");
        expandImg.src = imgs.src;
        imgText.innerHTML = imgs.alt;
        expandImg.parentElement.style.display = "block";
    }
</script>
</body>
</html>

FindImmo/templates/shop/index.html
<!--
author: W3layouts
author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
<title>Fetch Villa a Real Estate Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Fetch Villa Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->

<link href="{% static "css/bootstrap.css" %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" type="text/css" href="{% static "css/zoomslider.css" %}" />
<link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static "css/style.css" %}" rel="stylesheet">
<script type="text/javascript" src="{% static "js/modernizr-2.6.2.min.js" %}"></script>
<!--/web-fonts-->
<link href='//fonts.googleapis.com/css?family=Tangerine:400,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Lato:400,300,300italic,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!--//web-fonts-->
</head>
<body>
<!--/main-header-->
<div class="top-main" id="home">
   	<div class="header-top">
		<div class="w3l_header_left">
			<ul>
				<li><span class="fa fa-envelope" aria-hidden="true"></span> <a style="color:white;font-weight: bold;"href="mailto:info@example.com">info@example.com</a></li>
				<li  style="color:white;font-weight: bold;"><span class="fa fa-phone-square" aria-hidden="true"></span> (227) 96967600</li>
			</ul>
		</div>
		<div class="w3l_header_right">
			<ul class="top-links">
				<li><a href="{% url "shop:creation_vendeur" %}"><i class="fa fa-facebook"></i></a></li>
				<li><a href="#"><i class="fa fa-twitter"></i></a></li>
				<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
				<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
			</ul>
		</div>
		<div class="clearfix"> </div>
   	</div>
   	<div class="header-bottom">
   		<div class="mobile-container">

		<!-- Top Navigation Menu -->
		<div class="topnav">
		  <a href="{% url "shop:product_list" %}" class="active"><img src="{% static "images/miniLogo.png" %}" alt="w3ls" class="img-responsive" style="height:50px;"></a>
		  <div id="myLinks">
		    <a href="{% url "shop:product_list" %}">Acceuil</a>
		    <a href="{% url "shop:list_by_category" 'LOCATION' 'all' 'all' %}">En Location</a>
		    <a href="{% url "shop:list_by_category" 'VENTE' 'all' 'all' %}">En Vente</a>
		    <a href="{% url "shop:creation_vendeur" %}">Proposez un bien Immo</a>
		    <a href="#news">Gallérie</a>
		    <a href="#contact">Prestations</a>
		    <a href="#about">Contact</a>
		  </div>
		  <a href="javascript:void(0);" class="icon" onclick="myToggleMenu()">
		    <i class="fa fa-bars"></i>
		  </a>
		</div>
		</div>
		<nav class="navbar navbar-default">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
			  	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  	</button>
				<div class="logo">
					<div class="navbar-brand"></div>
				</div>
			</div>
		
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse nav-wil">
				<ul id="navmenu">
					<li><a href="{% url "shop:product_list" %}">Acceuil</a></li>
					<li><a href="#">Louer</a><span class="darrow">&#9660;</span>
						<ul class="sub1">
							{% for cat in categories %}
								{% if cat.slug != 'terrains' %}
								<li><a href="#">{{cat.name}}</a><span class="darrow hor">&#x25B8;</span>
									<ul class="sub2">
										<li><a href="{% url "shop:list_by_category" 'LOCATION' cat.slug 'VIDE'%}">Vide</a></li>
										<li><a href="{% url "shop:list_by_category" 'LOCATION' cat.slug 'MEUBLE'%}">meublee</a></li>
									</ul
								</li>
								{% else %}
								<li><a href="#">{{cat.name}}</a></li>
								{% endif %}
							{% endfor %}
							<li><a href="{% url "shop:list_by_category" 'LOCATION' 'all' 'all' %}">Tous types</a></li>
						</ul>
					</li>
					<li><a href="#">Acheter</a><span class="darrow">&#9660;</span>
						<ul class="sub1">
							{% for cat in categories %}
								{% if cat.slug != 'terrains' %}
								<li><a href="#">{{cat.name}}</a><span class="darrow hor">&#x25B8;</span>
									<ul class="sub2">
										<li><a href="{% url "shop:list_by_category" 'VENTE' cat.slug 'VIDE'%}">Vide</a></li>
										<li><a href="{% url "shop:list_by_category" 'VENTE' cat.slug 'MEUBLE'%}">meublee</a></li>
									</ul
								</li>
								{% else %}
								<li><a href="#">{{cat.name}}</a></li>
								{% endif %}
							{% endfor %}
							<li><a href="{% url "shop:list_by_category" 'VENTE' 'all' 'all' %}">Tous types</a></li>
						</ul>
					</li>
					<li><a href="{% url "shop:vendrebien" %}">Vendre</a></li>
					<li><a href="{% url "shop:prestation" %}">Prestations</a></li>
					<li><a href="{% url "shop:contact" %}">Contact</a></li>
					<!--<li><a href="{% url "shop:search" %}">search</a></li>-->
				</ul>
			</div>
		</nav>
		<!-- /.navbar-collapse -->
		<div class="w3ls_search">
			<ul class="cd-header-buttons">
				<li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
			</ul> <!-- cd-header-buttons -->
			<div id="cd-search" class="cd-search">
				<form action="#" method="post">
					<input name="Search" type="search" placeholder="Search...">
					<input type="submit" name="OK" value="OK">
				</form>
			</div>
		</div>
	</div>
	
	
</div>
<!--/main-header-->			

{% block content %}
{% endblock content%}

{% block content1 %}
{% endblock content1 %}

<!--/featured-projects-->
{% block content2 %}
{% endblock content2 %}

<!--Footer-->
<div class="contact-w3ls" id="contact">
<div class="container">
		<h2>Votre addresse email <span>pour les Newsletter</span></h2>
		<p class="para" style="font-size:0.6em;">Toutes les informations relevants de ce Site Web sont protegees par le 3WCC concorcium.
			ainsi libre est pour le proprietaire de poursuivre en justice toute tentative extortion ou re-utilisation des donnees de ce site.</p>
		<div class="footer-contact">
			<form action="#" method="post">
				<input type="text" name="Email" placeholder="Enter your email to update" required=" ">
				<input type="submit" value="Subscribe">
			</form>
		</div>
		
		<h3 class="text-center follow">Nous <span>suivre...</span></h3>
		<ul class="social-icons1 agileinfo">
			<li><a href="#"><i class="fa fa-facebook"></i></a></li>
			<li><a href="#"><i class="fa fa-twitter"></i></a></li>
			<li><a href="#"><i class="fa fa-whatsapp"></i></a></li>
			<li><a href="#"><i class="fa fa-youtube"></i></a></li>
			<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
		</ul>	
		<div class="w3agile_footer_copy">
		    <p>© 2019 hamdallaye immo. All rights reserved.</p>
		</div>
</div>
</div>
<a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>

<script src="{% static "js/jquery-1.11.1.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/jquery.zoomslider.min.js" %}"></script>
		<!-- search-jQuery -->
		<script src="{% static "js/main.js" %}"></script>
			<!-- //search-jQuery -->
			<script type="text/javascript">
				$(window).load(function() {
					$("#flexiselDemo1").flexisel({
						visibleItems:3,
						animationSpeed: 1000,
						autoPlay: true,
						autoPlaySpeed: 4000,    		
						pauseOnHover: true,
						enableResponsiveBreakpoints: true,
				    	responsiveBreakpoints: { 
				    		portrait: { 
				    			changePoint:480,
				    			visibleItems: 1
				    		}, 
				    		landscape: { 
				    			changePoint:640,
				    			visibleItems: 2
				    		},
				    		tablet: { 
				    			changePoint:768,
				    			visibleItems: 2
				    		}
				    	}
				    });
				    
				});
			</script>
			<script type="text/javascript" src="{% static "js/jquery.flexisel.js" %}"></script>

	<!-- Horizontal-Tabs-JavaScript -->
	<script src="{% static "js/easyResponsiveTabs.js" %}" type="text/javascript"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			$('#horizontalTab').easyResponsiveTabs({
				type: 'default',
				width: 'auto',
				fit: true,
			});
		});
	</script>
<!-- Horizontal-Tabs-JavaScript -->
<!-- <script src="{% static "js/jquery.picEyes.js" %}"></script> -->
<!-- <script>
	$(function(){
		//picturesEyes($('.demo li'));
		//$('.demo li').picEyes();
	});
</script> -->
	<!--start-smooth-scrolling-->
<!--/script-->
<script type="text/javascript" src="{% static "js/move-top.js" %}"></script>
<script type="text/javascript" src="{% static "js/easing.js" %}"></script>

<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){		
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
				});
			});
</script>
 <script type="text/javascript">
	$(document).ready(function() {
		/*
		var defaults = {
  			containerID: 'toTop', // fading element id
			containerHoverID: 'toTopHover', // fading element hover id
			scrollSpeed: 1200,
			easingType: 'linear' 
 		};
		*/
		
		$().UItoTop({ easingType: 'easeOutQuart' });
		
	});
</script>

<!--end-smooth-scrolling-->
<script>
function openPage(pageName,elmnt,color) {
	var i, tabcontent, tablinks;
	  tabcontent = document.getElementsByClassName("tabcontent");
	  for (i = 0; i < tabcontent.length; i++) {
	    tabcontent[i].style.display = "none";
	  }
	  tablinks = document.getElementsByClassName("tablink");
	  for (i = 0; i < tablinks.length; i++) {
	    tablinks[i].style.backgroundColor = "";
	  }
  document.getElementById(pageName).style.display = "block";
  elmnt.style.backgroundColor = color;
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script>
function FindMore() {
	var x = document.getElementsByClassName("reservation-grids");
	for (i = 0; i < x.length; i++){
		if (x[i].style.display === "none") {
	  		x[i].style.display = "block";
	  	} else {
	  		x[i].style.display = "none";
	}
  }
}
</script>
<script type="text/javascript">
function myFunction(imgs) {
    var expandImg = document.getElementById("expandedImg");
    var imgText = document.getElementById("imgtext");
    expandImg.src = imgs.src;
    imgText.innerHTML = imgs.alt;
    
}
</script>
<script>
function myToggleMenu() {
  var x = document.getElementById("myLinks");
  if (x.style.display === "block") {
    x.style.display = "none";
  } else {
    x.style.display = "block";
  }
}
</script>
<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  var captionText = document.getElementById("caption");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  captionText.innerHTML = dots[slideIndex-1].alt;
}
</script> 

</body>
</html>